---
title: "CodeBook.md"
output: html_document
---

This code book describes the variables, the data, and the work that was performed to clean up the data. The data that are being cleaned are from this site: 
http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones 

####The Data Files
The dataset has the following .txt files: 

- 'README.txt'

- 'features_info.txt': Shows information about the variables used on the feature vector.

- 'features.txt': List of all features.

- 'activity_labels.txt': Links the class labels with their activity name.

- 'train/X_train.txt': Training set.

- 'train/y_train.txt': Training labels.

- 'test/X_test.txt': Test set.

- 'test/y_test.txt': Test labels.

- 'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30 (number of subjects).

- 'test/subject_test.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30 (number of subjects).

####The Variables
The variables included in the datasets described above are as follows:

#####Activity labels
There are 6 activities that are performed by each of the 30 subjects. 

1 WALKING

2 WALKING_UPSTAIRS

3 WALKING_DOWNSTAIRS

4 SITTING

5 STANDING

6 LAYING

#####Features
There are 561 features. Due to the length of the list, they are not replicated here, but the reader is referred to the features.txt file. A short list is shown here, where XYZ represents the 3 axes that are represented in the larger features set. The features consist of various maesures, including the mean and std. Features are normalized and bounded within [-1,1].
The units used for the accelerations (total and body) are 'g's (gravity of earth -> 9.80665 m/seg2).The gyroscope units are rad/seg.

* tBodyAcc-XYZ
* tGravityAcc-XYZ
* tBodyAccJerk-XYZ
* tBodyGyro-XYZ
* tBodyGyroJerk-XYZ
* tBodyAccMag
* tGravityAccMag
* tBodyAccJerkMag
* tBodyGyroMag
* tBodyGyroJerkMag
* fBodyAcc-XYZ
* fBodyAccJerk-XYZ
* fBodyGyro-XYZ
* fBodyAccMag
* fBodyAccJerkMag
* fBodyGyroMag
* fBodyGyroJerkMag

This section is part of the Readme.md file

####Cleaning up the Data
The run_analysis.R program includes the 'plyr' library

The data are loaded from https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip and are unzipped into a folder "~/data/UCI HAR Dataset". This folder contains a "test"" and a "train" folder. A program, run_analysis.R, was written to do the following:

1. Merge the training and the test sets to create one data set.
+ Load the X_/Y_test, X_/Y_train and subject_test/train data from the "test"" and "train" folders, respectively. 
+ Join the train and test data, join the train and test labels and join the train and test subjects, by row

2. Extract only the measurements on the mean and standard deviation for each measurement. 
+ Load the features.txt data and find the rows that correspond to the mean and standard deviation measurements. These rows were designated with "mean() or "std()" at the end of the variable name. 
+ Use 'grep' to find which row numbers in the file have 'mean()' or 'std()' at the end of the feature name.
+ Apply these to the data columns and remove the '()' from the names 
+ Change the column names of the Subject and Label data sets from V1 to "Label" and "Subject"
+ Merge the Subjects, Labels and Data


3. Use descriptive activity names to name the activities in the data set.
+ Load the activity data, change the names in column 2 to lower case and remove the '-' from the names

4. Appropriately label the data set with descriptive variable names.
+ Clean up the column names in the merged data by removing '_' and converting names to lower case
+ This created a wide data set with column 1 being the Subject, column 2 being the activty and columns 3-68 representing the various measured mean and std

5. From the data set in step 4, create a second, independent tidy data set with the average of each variable for each activity and each subject.
+ Use ddply to capture the average of the columns by subject and activity
+ The resulting tidy data is in a wide format - each measured variable is in one column and each observation of that variable is in one row i.e. each of the 6 activities is reported once for each subject; each measured observation is in its own column. There are 180 observations over 68 variables (including the subject and activity)